version: '3'

services:

  redis:
    image: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Vladivostok
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata  # Маппинг томов
    ports:
      - '5433:5432'  # Маппинг портов
    healthcheck:  # Для проверки успешного старта базы данных
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    environment:
      TZ: Asia/Vladivostok
    command: python3 manage.py runserver 0.0.0.0:8000  # команды и ip для возможности открытия на любом интерфейсе
    ports:
      - '8000:8000'
    volumes:
      - .:/code  # Для подтягивания изменений в проекте на хостовой машине
    depends_on:
      db:
        condition: service_healthy  # Запуск только после базы данных

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data:
